import "./globals.css";
import { Besley } from "next/font/google";
import { ReactQueryClientProvider } from "@/utils/react-query";
import Footer from "./components/footer";

const besley = Besley({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className={besley.className}>
        <ReactQueryClientProvider>{children}</ReactQueryClientProvider>
        <Footer />
      </body>
    </html>
  );
}
